### PR TITLE
Minor typo fixed

### PR DESCRIPTION
**Pull request by karthikraman**

### CODE REVIEW

**Comment by shreevatsa** [comment]
Oops, thanks for catching the typo. Clearly this kind of code is error-prone, let me think about rewriting that part in a different way. (For the last 3 months or so I've been rewriting most of the code; currently I've been focusing on the "read" part.)

As for the E / O in HK, I don't think it's necessary (have you found that style of input anywhere?) — I prefer to be as conservative as possible; it's simple for the user to see error and fix their input, rather than to accept bad input and encourage more of it. :-)

(Actually there is a lot of similar stuff I'm doing: treat colon as visarga, treat short e and o as long e and o, etc... must reject all those inputs or at least show prominent warnings.)

**Comment by shreevatsa** [comment]
Actually it may be better to just fix the 'pada_3' for now; it's quite confusing (if someone looks at the debug output, that is). Can you remove the second commit, then I'll just merge this pull request?

**Comment by shreevatsa** [comment]
BTW thanks very much for looking at the code and finding bugs. :-)
I'd be interested to know what was particularly hard to understand, etc. (I know it's **all** very disorganized, but still...)

**Comment by karthikraman** [comment]
Oops, I meant you to pull only the typo fix. (I am still learning the ropes on GitHub). For HK, I use E and O, since it is then possible to include languages such as Tamil/Telugu, where there are shorter e and o's. I use this modified HK on stotrasamhita --- I don't think you should bother. Thanks! BTW, is there some simple read-up on metres? I think I should listen to Ganesh's talk.. He gave one at IISc too when I was around, and it was a lot of fun...

**Comment by vvasuki** [comment]
@karthikraman "BTW, is there some simple read-up on metres?"  https://sites.google.com/site/padyadhaaraa/

**Comment by vvasuki** [comment]
@shreevatsa ऎ / ए भेदश्च ऒ/ओ भेदश्च कल्पनीय इति मन्ये त्वद्यन्त्रे। स्मरामि पॆजत्ताय इति दाक्षिणात्यनामप्रयोक्तारम् अवधानिनं गणेशम्।

**Comment by shreevatsa** [comment]
@vvasuki The problem is that I've seen some people appear to have flawed input methods and type e.g. कॆ instead of के :-(
So overall a 'short e' or 'short o' input into the program seems to be more likely to be unintended (given that they don't occur natively in Sanskrit) rather than intended. That's why they're treated as long  https://github.com/shreevatsa/sanskrit/blame/9e85a8aba4a01e76b5016fcc22cfc0713b6a0435/transliteration/transliterate.py#L113,L116 ; otherwise it would be simple to treat them as short.

I have two plans for this:
- show warnings and offer to correct the character, and
- add a "manual" instead of "auto" mode where you can specify the input scheme instead of auto-detect (and auto fixes).

When I implement either of these two, this should be addressed.

**Pull request closed without merging**
